name: Valgrind
on:
  workflow_call:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
      extra_test_command:
        description: "Extra Test Command"
        type: string
        required: false
jobs:
  ndebug:
    name: No Assertions
    runs-on: [self-hosted, docker, builder]
    container:
      image: steinwurf/gcc-11.2.0:1.0.0
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
          GIT_SSH_COMMAND: ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes
        run: python3 waf configure --cxx_nodebug --git_protocol=git@ $EXTRA_RESOLVE_OPTIONS
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
      - name: Test
        env:
          EXTRA_TEST_COMMAND: ${{ inputs.extra_test_command }}
        run: python3 waf --run_tests $EXTRA_TEST_COMMAND
