name: No Assertions
on:
  workflow_call:
    inputs:
      preparation_commands:
        description: "Commands to run to prepare the build"
        required: false
        type: string
        default: ''
      extra_resolve_options:
        description: "Extra Resolve Options"
        type: string
        required: false
jobs:
  ndebug:
    name: No Assertions
    timeout-minutes: 45
    runs-on: [self-hosted, docker, builder]
    container:
      image: ghcr.io/steinwurf/gcc-12:1.0.0
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Preparation Commands
        if: inputs.preparation_commands != ''
        run: ${{ inputs.preparation_commands }}
      - name: Configure
        env:
          EXTRA_RESOLVE_OPTIONS: ${{ inputs.extra_resolve_options }}
          GIT_SSH_COMMAND: ssh -i /home/buildbot/.ssh/id_ed25519 -o IdentitiesOnly=yes
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: python3 waf configure --cxx_nodebug --git_protocol=git@ ${{ env.EXTRA_RESOLVE_OPTIONS }}
      - name: Build
        run: |
          echo "::add-matcher::.github/gcc-problem-matcher.json"
          python3 waf
